# Generated by Django 5.2.15 on 2026-06-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_primary',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='website_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='SV Biotech', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.JSONField(default=dict, help_text="JSON object with 'en' and 'mr' keys"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/'),
        ),
    ]
