# Generated by Django 5.2.15 on 2026-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, verbose_name='Address (English)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_mr',
            field=models.TextField(blank=True, verbose_name='Address (Marathi)'),
        ),
    ]
