# Generated by Django 5.2.15 on 2026-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sitesettings_address_sitesettings_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_mr',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Tupe Gold Farming', max_length=200),
        ),
    ]
