# Generated by Django 5.2.15 on 2026-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitesettings_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone2',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emails',
            field=models.TextField(blank=True, default='', help_text='Comma separated email addresses'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phones',
            field=models.TextField(blank=True, default='', help_text='Comma separated phone numbers'),
        ),
    ]
