# Generated by Django 5.2.15 on 2026-06-25 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_sitesettings_email_remove_sitesettings_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy address field', verbose_name='Primary Address (deprecated)'),
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Main Office', help_text='e.g. Registered Office, Branch Office', max_length=100)),
                ('address', models.TextField()),
                ('map_url', models.URLField(blank=True, help_text='Google Maps URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Office Address',
                'verbose_name_plural': 'Office Addresses',
                'ordering': ['order'],
            },
        ),
    ]
