# Generated by Django 5.2.15 on 2026-06-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropresult',
            old_name='after_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='before_image',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='result_text',
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='yield_increase_percentage',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='description',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='icon',
            field=models.CharField(blank=True, default='Leaf', help_text="Lucide icon name (e.g., 'Leaf', 'Sprout')", max_length=50),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='title',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='cropresult',
            name='crop_name',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
    ]
