# Generated by Django 5.2.15 on 2026-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_after_image_cropresult_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.RemoveField(
            model_name='benefititem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='benefititem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='crop_name',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='description',
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Text (English)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_text_mr',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Text (Marathi)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_en',
            field=models.TextField(blank=True, verbose_name='Subtitle (English)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_mr',
            field=models.TextField(blank=True, verbose_name='Subtitle (Marathi)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_mr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Marathi)'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='description_mr',
            field=models.TextField(blank=True, verbose_name='Description (Marathi)'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='title_mr',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Marathi)'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='crop_name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Crop Name (English)'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='crop_name_mr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Crop Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='description_mr',
            field=models.TextField(blank=True, verbose_name='Description (Marathi)'),
        ),
    ]
