# Generated by Django 5.2.15 on 2026-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_banner_cta_text_remove_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='cta_text_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cta_text_mr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_mr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_mr',
        ),
        migrations.RemoveField(
            model_name='benefititem',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='benefititem',
            name='description_mr',
        ),
        migrations.RemoveField(
            model_name='benefititem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='benefititem',
            name='title_mr',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='crop_name_en',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='crop_name_mr',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='cropresult',
            name='description_mr',
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Text'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='Subtitle'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='benefititem',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='crop_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Crop Name'),
        ),
        migrations.AddField(
            model_name='cropresult',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
