# Generated by Django 5.2.15 on 2026-06-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_banner_cta_text_en_remove_banner_cta_text_mr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cta_text',
        ),
    ]
