# Generated by Django 5.2.15 on 2026-06-25 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_banner_cta_link_remove_banner_cta_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropresult',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Display on Website'),
        ),
        migrations.AlterField(
            model_name='cropresult',
            name='image',
            field=models.ImageField(blank=True, help_text='Main thumbnail image', null=True, upload_to='crop_results/'),
        ),
        migrations.CreateModel(
            name='CropResultImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='crop_results/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('crop_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.cropresult')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
