# Generated by Django 5.2.15 on 2026-06-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AddField(
            model_name='product',
            name='crops_targeted',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='how_to_use',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.JSONField(blank=True, default=dict, help_text='Bilingual: {en, mr}'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
    ]
