# Generated by Django 5.2.15 on 2026-06-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_description_remove_product_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mr',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Display Name (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_name_mr',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Display Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Full Description (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_mr',
            field=models.TextField(blank=True, default='', verbose_name='Full Description (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mr',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.TextField(blank=True, default='', verbose_name='Short Description (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_mr',
            field=models.TextField(blank=True, default='', verbose_name='Short Description (Marathi)'),
        ),
    ]
