# Generated by Django 5.2.15 on 2026-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_category_name_remove_product_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_mr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name_mr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='full_description_mr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_mr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description_mr',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Category Display Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', verbose_name='Short Description'),
        ),
    ]
