# Generated by Django 5.2.15 on 2026-06-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_name_en_remove_category_name_mr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pack_sizes',
        ),
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('leaf', 'Leaf'), ('sprout', 'Sprout'), ('sun', 'Sun'), ('droplets', 'Droplets'), ('shield-check', 'Shield Check'), ('trending-up', 'Trending Up'), ('package', 'Package')], default='leaf', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PackSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='e.g. 1, 2.5, 500', max_length=50)),
                ('unit', models.CharField(help_text='e.g. Liter, Kg, Gram', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_sizes', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
