# Generated by Django 5.2.15 on 2026-06-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_benefits_remove_product_pack_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='crops_targeted',
        ),
        migrations.CreateModel(
            name='TargetedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_crops', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
