# Generated by Django 5.2.15 on 2026-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_crops_targeted_targetedcrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='packsize',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
