# Generated by Django 5.2.15 on 2026-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_packsize_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in Rupees', max_digits=10, null=True),
        ),
    ]
